services:
  traefik:
    image: "traefik:v3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.minecraft.address=:25565/tcp"
    ports:
      - "80:80"
      - "8080:8080"
      - "25565:25565"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   networks:
  #     - traefik
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"

networks:
  traefik:
    name: traefik
