services:
  minecraft_backuper:
    build: ./minecraft_backuper
    image: minecraft_backuper
    container_name: minecraft_backuper
    volumes:
      - type: bind
        source: /home/minecraft/conf
        target: /home/minecraft/mountpoint
    networks:
      - rcon
    expose:
      - 25575
    secrets:
      - mega_credentials
    environment:
      MEGA_CREDS: /run/secrets/mega_credentials

  minecraft_proxy:
    build: ./minecraft_proxy
    image: minecraft_proxy
    init: true
    container_name: minecraft_proxy
    command:
      - "--listener-socket-addr"
      - "0.0.0.0:25565"
      - "--server-socket-addr"
      - "minecraft_server:25565"
      - "--minecraft-version"
      - "1.21.1"
      - "--minecraft-protocol-version"
      - "767"
      - "--minecraft-description"
      - "Cool server"
      - "--minecraft-container-name"
      - "minecraft_server"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      traefik:
        aliases:
          - minecraft_proxy_traefik
      proxy:
        aliases:
          - minecraft_proxy_internal
    expose:
      - 25565
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.service=minecraft"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft.tls=false"

  minecraft_server:
    build: ./minecraft_server
    image: minecraft_server
    container_name: minecraft_server
    volumes:
      - type: bind
        source: /home/minecraft/conf
        target: /home/minecraft/conf
    networks:
      - proxy
      - rcon
    expose:
      - 25565
      - 25575
    stdin_open: true
    tty: true

networks:
  proxy: {}
  rcon: {}
  traefik:
    external: true

secrets:
  mega_credentials:
    file: mega_credentials

volumes:
    server_data:
