services:
  minecraft_backuper:
    build: ./minecraft_backuper
    image: minecraft_backuper
    container_name: minecraft_backuper
    volumes:
      - type: bind
        source: /home/minecraft/conf
        target: /home/minecraft/mountpoint
    networks:
      - rcon
    expose:
      - 25575
    secrets:
      - mega_credentials
    environment:
      MEGA_CREDS: /run/secrets/mega_credentials

  minecraft_proxy:
    image: itzg/mc-router
    container_name: minecraft_proxy
    depends_on:
      - minecraft_server
    environment:
      - "TRACE=true"
      - "IN_DOCKER=true"
      - "AUTO_SCALE_DOWN=true"
      - "AUTO_SCALE_UP=true"
      - "AUTO_SCALE_DOWN_AFTER=15m"
      - "AUTO_SCALE_ASLEEP_MOTD=Server stopped. Join to start it !"
      - "AUTO_SCALE_LOADING_MOTD=Server starting. Please bear with us..."
      - "TZ=Europe/Paris"
    expose:
      - 25565
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.service=minecraft"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft.tls=false"
    networks:
      - traefik
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  minecraft_server:
    build: ./minecraft_server
    image: minecraft_server
    container_name: minecraft_server
    volumes:
      - type: bind
        source: /home/minecraft/conf
        target: /home/minecraft/conf
    networks:
      - proxy
      - rcon
    expose:
      - 25565
      - 25575
    labels:
      - "mc-router.host=minecraft.debilausau.re"
      - "mc-router.network=minecraft_proxy"
    stdin_open: true
    tty: true

networks:
  proxy: {}
  rcon: {}
  traefik:
    external: true

secrets:
  mega_credentials:
    file: mega_credentials

volumes:
    server_data:
